import type { Metadata } from "next";
import "./globals.css";
// import { Navbar } from "@/components/common/Navbar";
import { AuthProvider } from "@/context/AuthProvider";
import { ThemeProvider } from "next-themes";
import { Providers } from "./providers";



export const metadata: Metadata = {
  title: "PrepPath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // client
  // const queryClient = new QueryClient()

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased flex justify-center items-center flex-col`}
      >
        <Providers>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            {/* <Navbar /> */}
            {children}
          </AuthProvider>
        </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
